# Generated by Django 3.2.20 on 2023-12-13 05:30

from django.db import migrations, IntegrityError
import uuid


def forward_func(apps, schema_editor):
    Ticket = apps.get_model("ticket", "Ticket")
    for row in range(1000000):
        try:
            Ticket.objects.create(token=uuid.uuid4())
        except IntegrityError:
            _uuid = uuid.uuid4()
            while Ticket.objects.filter(token=_uuid).count():
                _uuid = uuid.uuid4()
            Ticket.objects.create(token=_uuid)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func),
    ]
